version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ""
    groups:
      fastapi-stack:
        patterns:
          - "fastapi"
          - "uvicorn*"
          - "pydantic*"
      google-stack:
        patterns:
          - "google*"